name: Auto Versioning
on:
  push:
    branches: [main]
jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Read and increment version
      run: |
        current_version=$(cat version.txt | sed 's/v//')
        IFS='.' read -r major minor patch <<< "$current_version"
        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"
        echo $new_version > version.txt
    - name: Commit new version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.txt
        git commit -m "Auto-increment version to $(cat version.txt)"
        git push
